name: 'splash_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'splash_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  splash_analytics:
    # Config indicated by + and applies to all files under models/
    +materialized: table
    staging:
      +materialized: view
    marts:
      +materialized: table
    intermediate:
      +materialized: view

# Global variables
vars:
  # Date range for incremental models
  start_date: '2024-01-01'
  
# Seeds configuration
seeds:
  splash_analytics:
    +quote_columns: false

# Tests configuration  
tests:
  +store_failures: true 