splash_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', '') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('POSTGRES_DB', 'postgres') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      
    prod:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10 